// Generated by CoffeeScript 1.7.1
(function() {
  angular.module("Angustrap", []).directive("btnGlyph", function($timeout) {
    var defObj;
    defObj = {
      restrict: "E",
      replace: true,
      transclude: true,
      templateUrl: "templates/dropdowns/btn-glyph.html",
      scope: {
        icon: "@icon",
        theme: "@theme",
        size: "@size"
      },
      link: function(scope, el, attrs) {
        console.log(el);
        return attrs.theme = attrs.theme || "default";
      }
    };
    return defObj;
  });

}).call(this);

//# sourceMappingURL=btn-glyph.map
