// Generated by CoffeeScript 1.6.3
(function() {
  directive("btnGlyph", [
    function($timeout) {
      var defObj;
      defObj = {
        restrict: "E",
        replace: true,
        transclude: true,
        scope: {
          icon: "@",
          theme: "@",
          size: "@"
        },
        link: function(scope, el, attrs) {
          return attrs.theme = attrs.theme || "default";
        },
        template: '\
            <button type="button" class="btn btn-{{theme}} btn-{{size}}">\
                <span class="glyphicon glyphicon-{{icon}}"></span>\
                <span data-ng-transclude></span>\
            </button>'
      };
      return defObj;
    }
  ]);

}).call(this);

/*
//@ sourceMappingURL=btn-glyph.map
*/
