// Generated by CoffeeScript 1.6.3
(function() {
  directive("glyph", [
    function() {
      var defObj;
      defObj = {
        restrict: "E",
        replace: window.replace,
        template: "<span id=\"{{asId}}\" class=\"glyphicon glyphicon-{{icon}} {{asClass}}\"></span>",
        scope: {
          icon: "@icon",
          asId: "@asId",
          asClass: "@asClass"
        }
      };
      return defObj;
    }
  ]);

}).call(this);

/*
//@ sourceMappingURL=glyph.map
*/
