// Generated by CoffeeScript 1.6.3
(function() {
  directive("glyph", [
    function() {
      var defObj;
      defObj = {
        restrict: "E",
        replace: true,
        template: '<span class=\"glyphicon glyphicon-{{icon}}\"></span>',
        scope: {
          icon: "@icon"
        }
      };
      return defObj;
    }
  ]);

}).call(this);

/*
//@ sourceMappingURL=glyph.map
*/
