// Generated by CoffeeScript 1.6.3
(function() {
  window.replace = false;

  angular.module("Angustrap", []).service('AsRandom', function() {
    return function(x) {
      var r, s;
      s = "";
      while (s.length < x && x > 0) {
        r = Math.random();
        s += (r < 0.1 ? Math.floor(r * 100) : String.fromCharCode(Math.floor(r * 26) + (r > 0.5 ? 97 : 65)));
      }
      return s;
    };
  }).service('CleanUp', function($timeout) {
    return function(scope) {
      return $timeout(function() {
        var classes;
        if (scope.asId) {
          classes = $('#' + scope.asId).attr('class');
          return $('#' + scope.asId).attr('class', classes.trim());
        }
      }, 0);
    };
  }).directive("glyph", function() {
    var defObj;
    defObj = {
      restrict: "E",
      replace: true,
      template: "<span id=\"{{asId}}\" class=\"glyphicon glyphicon-{{icon}} {{asClass}}\"></span>",
      scope: {
        icon: "@icon",
        asId: "@asId",
        asClass: "@asClass"
      }
    };
    return defObj;
  }).directive("btnGlyph", function($timeout) {
    var defObj;
    defObj = {
      restrict: "E",
      replace: true,
      transclude: true,
      templateUrl: "templates/dropdowns/btn-glyph.html",
      scope: {
        icon: "@icon",
        theme: "@theme",
        size: "@size"
      },
      link: function(scope, el, attrs) {
        return attrs.theme = attrs.theme || "default";
      }
    };
    return defObj;
  }).directive("listItem", function() {
    var defObj;
    defObj = {
      restrict: "E",
      replace: true,
      transclude: true,
      templateUrl: "templates/dropdowns/dropdown-item.html",
      scope: {
        asHref: "@asHref"
      }
    };
    return defObj;
  }).directive("listDivider", function() {
    var defObj;
    defObj = {
      restrict: "E",
      replace: true,
      scope: {},
      template: "<li role=\"presentation\" class=\"divider\"></li>"
    };
    return defObj;
  }).directive("dropdown", function() {
    var defObj;
    defObj = {
      restrict: "E",
      replace: true,
      transclude: true,
      templateUrl: "templates/dropdowns/dropdown.html",
      scope: {
        type: "@type",
        theme: "@theme",
        icon: "@icon",
        size: "@size",
        title: "@title",
        dropup: "=dropup",
        asClick: "=asClick"
      },
      link: {
        pre: function(scope) {
          if (scope.dropup) {
            scope.directionClass = "dropup";
          } else {
            scope.directionClass = "dropdown";
          }
          if (scope.type === "split") {
            scope.isSplit = true;
            return scope.btnGroup = "btn-group";
          } else if (scope.type === "btn") {
            scope.isSplit = false;
            scope.srOnly = "";
            return scope.btnGroup = "";
          } else if (!scope.type) {
            scope.srOnly = "sr-only";
            scope.isSplit = false;
            return scope.btnGroup = "";
          }
        }
      }
    };
    return defObj;
  }).directive("btnDropdown", function() {
    var defObj;
    defObj = {
      restrict: "E",
      replace: true,
      transclude: true,
      templateUrl: "templates/dropdowns/btn-dropdown.html",
      scope: {
        theme: "@theme",
        size: "@size",
        title: "@title",
        dropup: "=dropup"
      },
      link: function(scope, el, attrs) {
        attrs.theme = attrs.theme || "default";
        if (scope.dropup) {
          scope.directionClass = "dropup";
        }
        console.e("The <btn-dropdown> directive is now deprecated. Please use <dropdown type='btn'> instead");
      }
    };
    return defObj;
  }).directive("splitDropdown", function() {
    var defObj;
    defObj = {
      restrict: "E",
      replace: true,
      transclude: true,
      templateUrl: "templates/dropdowns/split-dropdown.html",
      scope: {
        theme: "@theme",
        icon: "@icon",
        size: "@size",
        title: "@title",
        dropup: "=dropup"
      },
      link: function(scope, el, attrs) {
        attrs.theme = attrs.theme || "default";
        if (scope.dropup) {
          scope.directionClass = "dropup";
        }
        console.e("The <split-dropdown> directive is now deprecated. Please use <dropdown type='split'> instead");
      }
    };
    return defObj;
  }).directive("navbar", [
    'AsRandom', function(AsRandom) {
      return {
        restrict: "E",
        replace: true,
        transclude: true,
        templateUrl: "templates/navbar.html",
        scope: {
          theme: "@theme",
          title: "@title",
          titleHref: "@titleHref",
          fixed: "@fixed",
          asId: "@asId",
          asClass: "@asClass"
        },
        controller: function($scope, $timeout, CleanUp) {
          $scope.random = '#' + AsRandom(12);
          if (!$scope.theme) {
            $scope.theme = "default";
          }
          if ($scope.fixed) {
            $scope.fixedWildcard = "navbar-fixed-";
          }
          if (!$scope.fixed || scope.fixed === "static") {
            $scope.fixedWildcard = "navbar-static-top";
          }
          return CleanUp($scope);
        }
      };
    }
  ]).directive("navbarList", function() {
    return {
      restrict: "E",
      replace: true,
      transclude: true,
      template: "<ul class=\"nav navbar-nav {{wildcard}}{{side}}\" data-ng-transclude></ul>",
      scope: {
        asId: "@asId",
        asClass: "@asClass",
        side: "@side"
      },
      controller: function($scope, CleanUp) {
        if ($scope.side) {
          $scope.wildcard = "navbar-";
        } else {
          $scope.wildcard = "";
        }
        return CleanUp($scope);
      }
    };
  }).directive("navbarDropdown", function() {
    return {
      restrict: "E",
      replace: true,
      transclude: true,
      scope: {
        asId: "@asId",
        asClass: "@asClass",
        title: "@title"
      },
      controller: function($scope, CleanUp) {
        return CleanUp($scope);
      },
      template: "<li class=\"dropdown {{asClass}}\" id=\"{{asId}}\">\n    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">{{title}} <b class=\"caret\"></b></a>\n    <ul class=\"dropdown-menu\" data-ng-transclude></ul>\n</li>"
    };
  }).directive("inputGroup", function() {
    return {
      restrict: "E",
      replace: true,
      templateUrl: "templates/inputs/input-group.html",
      scope: {
        asId: "@asId",
        asClass: "@asClass",
        title: "@title",
        type: "@type",
        inputType: "@inputType",
        side: "@side",
        theme: "@theme"
      }
    };
  });

  (function() {
    var e, n, r, t;
    r = function(t) {
      return function(r, i) {
        return e.log("%c" + r, i + ";color:#fff;background:" + n[1][t]);
      };
    };
    e = console;
    t = 3;
    n = [["e", "s", "i"], ["#c0392b", "#2ecc71", "#3498db"]];
    while (t--) {
      e[n[0][t]] = r(t);
    }
  })();

}).call(this);

/*
//@ sourceMappingURL=angustrap.map
*/
