// Generated by CoffeeScript 1.6.3
(function() {
  angular.module("Angustrap").directive("inputGroup", function() {
    return {
      restrict: "E",
      replace: true,
      templateUrl: "templates/inputs/input-group.html",
      scope: {
        asId: "@asId",
        asClass: "@asClass",
        title: "@title",
        type: "@type",
        inputType: "@inputType",
        side: "@side",
        size: "@size",
        theme: "@theme"
      },
      controller: function($scope, CleanUp) {
        $scope.sizeWildcard = "input-group-";
        return CleanUp($scope);
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=input-group.map
*/
