// Generated by CoffeeScript 1.6.3
(function() {
  directive("asLabel", [
    function() {
      var defObj;
      defObj = {
        restrict: "E",
        replace: true,
        transclude: true,
        template: '<span class="label label-{{theme}}" data-ng-transclude></span>',
        scope: {
          theme: "@"
        },
        link: function(scope, el, attrs) {
          if (!attrs.theme) {
            return attrs.theme = "default";
          }
        }
      };
      return defObj;
    }
  ]);

}).call(this);

/*
//@ sourceMappingURL=label.map
*/
