// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('Angustrap').directive("dropdown", function() {
    var defObj;
    defObj = {
      restrict: "E",
      replace: true,
      transclude: true,
      templateUrl: "templates/dropdowns/dropdown.html",
      scope: {
        dropup: "@dropup"
      },
      link: function(scope) {
        if (scope.dropup) {
          return scope.directionClass = "dropup";
        } else {
          return scope.directionClass = "dropdown";
        }
      }
    };
    return defObj;
  });

}).call(this);

/*
//@ sourceMappingURL=dropdown.map
*/
