// Generated by CoffeeScript 1.7.1
(function() {
  angular.module("Angustrap").directive("dropdown", function() {
    var defObj;
    defObj = {
      restrict: "E",
      replace: true,
      transclude: true,
      templateUrl: "templates/dropdowns/dropdown.html",
      scope: {
        asId: "@asId"
      }
    };
    return defObj;
  });

}).call(this);

//# sourceMappingURL=dropdown.map
