// Generated by CoffeeScript 1.7.1
(function() {
  angular.module("Angustrap").directive("dropdownItem", function() {
    var defObj;
    defObj = {
      restrict: "E",
      replace: true,
      transclude: true,
      templateUrl: "templates/dropdowns/dropdown-item.html",
      scope: {
        asHref: "@asHref"
      }
    };
    return defObj;
  });

}).call(this);

//# sourceMappingURL=dropdown-item.map
