// Generated by CoffeeScript 1.6.3
(function() {
  service('AsRandom', [
    function() {
      return function(x) {
        var r, s;
        s = "";
        while (s.length < x && x > 0) {
          r = Math.random();
          s += (r < 0.1 ? ~~(r * 100) : String.fromCharCode(~~(r * 26) + (r > 0.5 ? 97 : 65)));
        }
        return s;
      };
    }
  ]);

}).call(this);

/*
//@ sourceMappingURL=as-random.map
*/
