// Generated by CoffeeScript 1.7.1
(function() {
  directive("progressBar", [
    function() {
      return {
        restrict: "E",
        transclude: false,
        replace: true,
        scope: {
          theme: "@",
          currValue: "@",
          minValue: "@",
          maxValue: "@",
          asTitle: "@"
        },
        template: '<div class="progress"> <div class="progress-bar progress-bar-{{theme}}" role="progressbar" aria-valuenow="{{currValue}}" aria-valuemin="{{minValue}}" aria-valuemax="{{maxValue}}" style="width: {{currValue}}%"> <span class="sr-only">{{asTitle}}</span> </div> </div'
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=progressbar.map
