// Generated by CoffeeScript 1.6.3
(function() {
  directive("progressBar", [
    function() {
      return {
        restrict: "E",
        transclude: false,
        replace: true,
        scope: {
          theme: "@",
          current: "@",
          title: "@",
          striped: "@",
          animated: "@"
        },
        template: '\
    <div class="progress">\
      <div class="progress-bar progress-bar-{{theme}} {{striped ? \'progress-bar-striped\' : \'\'}} {{animated ? \'active\' : \'\'}}" role="progressbar" aria-valuenow="{{current}}" aria-valuemin="0" aria-valuemax="100" style="width: {{current}}%">\
        <span class="sr-only">{{title}}</span>\
        {{title}}\
      </div>\
    </div',
        link: function(scope, el, attrs) {
          if (attrs.striped === "") {
            attrs.striped = true;
          }
          if (attrs.animated === "") {
            return attrs.animated = true;
          }
        }
      };
    }
  ]);

}).call(this);

/*
//@ sourceMappingURL=progressbar.map
*/
