// Generated by CoffeeScript 1.6.3
(function() {
  directive("dropdown", [
    function() {
      var defObj;
      defObj = {
        restrict: "E",
        replace: true,
        transclude: true,
        scope: {
          type: "@type",
          theme: "@theme",
          icon: "@icon",
          size: "@size",
          title: "@title",
          dropup: "=dropup",
          asClick: "=asClick"
        },
        template: '\
            <div class="{{btnGroup}} {{directionClass}}">\
                <button type="button" class="btn btn-{{theme}} btn-{{size}}" data-toggle="{{dataToggle}}">\
                    <glyph icon="{{icon}}"></glyph> {{title}}\
                    <span class="caret" data-ng-hide="isSplit"></span>\
                </button>\
                <button type="button" class="btn btn-{{theme}} btn-{{size}} dropdown-toggle" data-toggle="dropdown" data-ng-show="isSplit">\
                    <span class="caret"></span>\
                    <span class="sr-only" style="position: relative"></span>\
                </button>\
                <ul class="dropdown-menu" role="menu" data-ng-transclude></ul>\
            </div>',
        controller: [
          '$scope', 'CleanUp', function($scope, CleanUp) {
            if ($scope.dropup) {
              $scope.directionClass = "dropup";
            } else {
              $scope.directionClass = "dropdown";
            }
            if ($scope.type === "split") {
              $scope.isSplit = true;
              $scope.dataToggle = "";
              $scope.btnGroup = "btn-group";
            } else if ($scope.type === "btn" || !$scope.type) {
              $scope.isSplit = false;
              $scope.dataToggle = "dropdown";
              $scope.btnGroup = "";
            }
            return CleanUp($scope);
          }
        ]
      };
      return defObj;
    }
  ]);

}).call(this);

/*
//@ sourceMappingURL=dropdown.map
*/
