// Generated by CoffeeScript 1.7.1
(function() {
  angular.module("Angustrap", []).directive("dropdownDivider", function() {
    var defObj;
    defObj = {
      restrict: "E",
      replace: true,
      scope: {},
      template: "<li role=\"presentation\" class=\"divider\"></li>"
    };
    return defObj;
  });

}).call(this);

//# sourceMappingURL=dropdown-divider.map
