// Generated by CoffeeScript 1.6.3
(function() {
  directive("dropdown", [
    function() {
      var defObj;
      defObj = {
        restrict: "E",
        replace: true,
        transclude: true,
        scope: {
          type: "@type",
          theme: "@theme",
          icon: "@icon",
          size: "@size",
          title: "@title",
          dropup: "=dropup",
          asClick: "=asClick"
        },
        template: "<div class=\"{{btnGroup}} {{directionClass}}\">\n    <button type=\"button\" class=\"btn btn-{{theme}} btn-{{size}}\" data-toggle=\"{{dataToggle}}\">\n        <glyph icon=\"{{icon}}\" ng-show=\"isSplit\" style=\"font-size: 0.95em\"></glyph>\n        <glyph icon=\"{{icon}}\" ng-hide=\"isSplit\"></glyph>\n         {{title}}\n        <span class=\"caret\" data-ng-hide=\"isSplit\"></span>\n    </button>\n    <button type=\"button\" class=\"btn btn-{{theme}} btn-{{size}} dropdown-toggle\" data-toggle=\"dropdown\" data-ng-show=\"isSplit\">\n        <span class=\"caret\"></span>\n        <span class=\"sr-only\" style=\"position: relative\"></span>\n    </button>\n    <ul class=\"dropdown-menu\" role=\"menu\" data-ng-transclude></ul>\n</div>",
        controller: [
          '$scope', 'CleanUp', function($scope, CleanUp) {
            if (!$scope.size) {
              $scope.size = "";
            }
            if ($scope.dropup) {
              $scope.directionClass = "dropup";
            } else {
              $scope.directionClass = "";
            }
            if ($scope.type === "split") {
              $scope.isSplit = true;
              $scope.dataToggle = "";
              $scope.btnGroup = "btn-group";
            } else if ($scope.type === "btn" || !$scope.type) {
              $scope.isSplit = false;
              $scope.dataToggle = "dropdown";
              $scope.btnGroup = "";
            }
            return CleanUp($scope);
          }
        ]
      };
      return defObj;
    }
  ]);

}).call(this);

/*
//@ sourceMappingURL=dropdown.map
*/
