// Generated by CoffeeScript 1.6.3
(function() {
  directive("dropdown", [
    function() {
      var defObj;
      defObj = {
        restrict: "E",
        replace: true,
        transclude: true,
        scope: {
          type: "@",
          theme: "@",
          icon: "@",
          size: "@",
          title: "@",
          dropup: "=",
          asClick: "="
        },
        template: '\
            <div class="{{btnGroup}} {{directionClass}}">\
                <button type="button" class="btn btn-{{theme}} btn-{{size}}" data-toggle="{{dataToggle}}">\
                    <glyph icon="{{icon}}"></glyph> {{title}}\
                    <span class="caret" data-ng-hide="isSplit"></span>\
                </button>\
                <button type="button" class="btn btn-{{theme}} btn-{{size}} dropdown-toggle" data-toggle="dropdown" data-ng-show="isSplit" style="height: {{caretHeight}}px">\
                    <span class="caret"></span>\
                    <span class="sr-only" style="position: relative"></span>\
                </button>\
                <ul class="dropdown-menu" role="menu" data-ng-transclude></ul>\
            </div>',
        controller: [
          '$scope', 'CleanUp', function($scope, CleanUp) {
            $scope.caretHeight = 34;
            if ($scope.dropup) {
              $scope.directionClass = "dropup";
            } else {
              $scope.directionClass = "dropdown";
            }
            if ($scope.size === "lg") {
              $scope.caretHeight = 46;
            } else if ($scope.size === "sm") {
              $scope.caretHeight = 30;
            }
            if ($scope.type === "split") {
              $scope.isSplit = true;
              $scope.dataToggle = "";
              $scope.btnGroup = "btn-group";
            } else if ($scope.type === "btn" || !$scope.type) {
              $scope.isSplit = false;
              $scope.dataToggle = "dropdown";
              $scope.btnGroup = "";
            }
            return CleanUp($scope);
          }
        ]
      };
      return defObj;
    }
  ]);

}).call(this);

/*
//@ sourceMappingURL=dropdown.map
*/
