// Generated by CoffeeScript 1.6.3
(function() {
  directive("listDivider", [
    function() {
      var defObj;
      defObj = {
        restrict: "E",
        replace: true,
        scope: {},
        template: '<li role="presentation" class="divider"></li>'
      };
      return defObj;
    }
  ]);

}).call(this);

/*
//@ sourceMappingURL=list-divider.map
*/
