// Generated by CoffeeScript 1.7.1
(function() {
  directive("listItem", [
    function() {
      var defObj;
      defObj = {
        restrict: "E",
        replace: true,
        transclude: true,
        scope: {
          asHref: "@asHref"
        },
        template: "<li role=\"presentation\">\n  <a role=\"menuitem\" tabindex=\"-1\" href=\"{{asHref}}\" data-ng-transclude></a>\n</li>"
      };
      return defObj;
    }
  ]);

}).call(this);

//# sourceMappingURL=list-item.map
