// Generated by CoffeeScript 1.6.3
(function() {
  directive("listItem", [
    function() {
      var defObj;
      defObj = {
        restrict: "E",
        replace: true,
        transclude: true,
        scope: {
          asHref: "@"
        },
        template: '\
        <li role="presentation">\
          <a role="menuitem" tabindex="-1" href="{{asHref}}" data-ng-transclude></a>\
        </li>'
      };
      return defObj;
    }
  ]);

}).call(this);

/*
//@ sourceMappingURL=list-item.map
*/
