// Generated by CoffeeScript 1.7.1
(function() {
  directive("navbarList", [
    function() {
      return {
        restrict: "E",
        replace: true,
        transclude: true,
        template: '<ul class="nav navbar-nav {{wildcard}}{{side}}" data-ng-transclude></ul>',
        scope: {
          side: "@side"
        },
        controller: [
          '$scope', 'CleanUp', function($scope, CleanUp) {
            if ($scope.side) {
              $scope.wildcard = "navbar-";
            } else {
              $scope.wildcard = "";
            }
            return CleanUp($scope);
          }
        ]
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=navbar-list.map
