// Generated by CoffeeScript 1.6.3
(function() {
  angular.module("Angustrap").directive("navbar", [
    'AsRandom', function(AsRandom) {
      return {
        restrict: "E",
        replace: true,
        transclude: true,
        templateUrl: "templates/navbar.html",
        scope: {
          theme: "=?",
          title: "@title",
          titleHref: "@titleHref",
          fixed: "@fixed",
          asId: "@asId",
          asClass: "@asClass"
        },
        controller: function($scope, $timeout, CleanUp) {
          $scope.random = '#' + AsRandom(12);
          if (!$scope.theme) {
            $scope.theme = "default";
          }
          if ($scope.fixed === "bottom") {
            $scope.fixedWildcard = "navbar-fixed-";
          } else if ($scope.fixed === "top") {
            $scope.fixedWildcard = "navbar-static-";
          } else {
            $scope.fixedWildcard = "";
          }
          return CleanUp($scope);
        }
      };
    }
  ]);

}).call(this);

/*
//@ sourceMappingURL=navbar.map
*/
