// Generated by CoffeeScript 1.6.3
(function() {
  directive("alert", [
    function() {
      var defObj;
      defObj = {
        restrict: "E",
        replace: true,
        transclude: true,
        scope: {
          theme: "@",
          dismissible: "@"
        },
        template: '<div class="alert alert-{{theme}} {{dismissible ? alert-dismissible : \'\' }}" role="alert">\
                           <button type="button" class="close" data-dismiss="alert" data-ng-show="dismissible">\
                               <span aria-hidden="true">&times;</span>\
                               <span class="sr-only">Close</span>\
                           </button>\
                           <div data-ng-transclude></div>\
                       </div>',
        link: function(scope, el, attrs) {
          if (attrs.dismissible === "") {
            return attrs.dismissible = true;
          }
        }
      };
      return defObj;
    }
  ]);

}).call(this);

/*
//@ sourceMappingURL=alerts.map
*/
